import type { Metadata } from "next";
import { Bree_Serif } from "next/font/google";
import "./globals.css";
import Provider from "./provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const breeSerif = Bree_Serif({subsets: ['latin'], weight: '400'});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      className={breeSerif.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
